# Generated by Django 5.1.3 on 2024-11-30 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('ajudante', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=8, unique=True)),
                ('km', models.IntegerField(blank=True, default=0, null=True)),
                ('tara', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('placa_veiculo',),
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('motorista', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='tab_td',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('saida_base', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'ordering': ('-saida_base',),
            },
        ),
        migrations.CreateModel(
            name='Cargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('p2', models.IntegerField(blank=True, default=0, null=True)),
                ('p5', models.IntegerField(blank=True, default=0, null=True)),
                ('p8', models.IntegerField(blank=True, default=0, null=True)),
                ('p13', models.IntegerField(blank=True, default=0, null=True)),
                ('p20', models.IntegerField(blank=True, default=0, null=True)),
                ('p45', models.IntegerField(blank=True, default=0, null=True)),
                ('cor', models.CharField(blank=True, choices=[('CINZA', 'cinza'), ('VERDE', 'verde')], max_length=5)),
                ('Carga_Placa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carga_placa', to='db_mvhs.caminhao')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='epis_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('epis', models.CharField(blank=True, choices=[('LUVA', 'luva'), ('CAPACETE', 'capacete'), ('OCLULOS', 'oculos'), ('PROTETOR DE OUVIDO', 'protetor de ouvido'), ('PROTETOR SOLAR', 'protetor solar')], max_length=30, null=True)),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('link_descricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_descricao', to='db_mvhs.caminhao')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Manutencao_Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('Agendado', models.DateField(verbose_name='Data: Agendada')),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('link_agendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_agendado', to='db_mvhs.caminhao')),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(default=0)),
                ('horimetro', models.IntegerField(default=0)),
                ('Litros', models.IntegerField(default=0)),
                ('hodometro', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('hora', models.TimeField(auto_now_add=True, max_length=5, verbose_name='criado em')),
                ('responsave_abastecimento', models.CharField(max_length=30)),
                ('Abastecimento_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimento_pĺacas', to='db_mvhs.caminhao')),
                ('Nome_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nome_motoristas', to='db_mvhs.motorista')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
        migrations.CreateModel(
            name='outros_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('outros', models.CharField(blank=True, max_length=20, null=True, verbose_name='outros')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Revenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(blank=True, choices=[('SAIDA', 'saida'), ('REVENDA', 'revenda'), ('RETORNO', 'retorno')], max_length=7)),
                ('km', models.IntegerField(blank=True, default=0, null=True)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_cliente', models.IntegerField(blank=True, default=0, null=True)),
                ('nota_1', models.IntegerField(blank=True, default=0, null=True)),
                ('nota_2', models.IntegerField(blank=True, default=0, null=True)),
                ('p2', models.IntegerField(blank=True, default=0, null=True)),
                ('p5', models.IntegerField(blank=True, default=0, null=True)),
                ('p8', models.IntegerField(blank=True, default=0, null=True)),
                ('p13', models.IntegerField(blank=True, default=0, null=True)),
                ('p20', models.IntegerField(blank=True, default=0, null=True)),
                ('p45', models.IntegerField(blank=True, default=0, null=True)),
                ('entrada', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('OBS', models.CharField(blank=True, max_length=254, null=True)),
                ('link_Ajudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_ajudantes', to='db_mvhs.ajudante')),
                ('link_caminhao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_caminhaos', to='db_mvhs.caminhao')),
                ('link_motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_motoristas', to='db_mvhs.motorista')),
                ('link_td', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_tds', to='db_mvhs.tab_td')),
            ],
            options={
                'ordering': ('-entrada',),
            },
        ),
        migrations.CreateModel(
            name='uniformes_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='criado em')),
                ('tipo', models.CharField(blank=True, choices=[('CAMISA', 'camisa'), ('CALÇA', 'calça'), ('BOTA', 'bota'), ('BONÉ', 'boné')], max_length=30, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='tamanho')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniformes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data',),
            },
        ),
    ]
