# Generated by Django 5.1.3 on 2024-12-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_mvhs', '0002_tab_td_link_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_td',
            name='link_Usuario',
        ),
    ]
