# Generated by Django 5.1.3 on 2024-12-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_mvhs', '0003_remove_tab_td_link_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_td',
            name='link_reponsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_reponsavel', to='db_mvhs.motorista'),
        ),
    ]
